<?php

return [
    [
        'type_id'       => '1',
        "title"         => "SpotifyWeb",
        "user_id"       => "1",
        "creation_date" => "2023-03-22",
        "last_update"   => "2023-03-27",
        "collaborators" => "",
        "description"   => "clone of spotify",
        "image1"        => "/01SpotifyWeb.jpeg",
        "image2"        => "",
        "image3"        => "",
        "image4"        => "",
        "image5"        => "",
        "video"         => "/01SpotifyWeb.mp4",
        "technologies"  => [1, 2, 3],
        "link_github"   => "https://github.com/AlessioAbbati/html-css-spotifyweb.git",
    ],
    [
        'type_id'       => '1',
        "title"         => "Minefield",
        "user_id"       => "1",
        "creation_date" => "2023-04-26",
        "last_update"   => "2023-04-26",
        "collaborators" => "",
        "description"   => "clone of minefield",
        "image1"        => "/01Campominato.jpeg",
        "image2"        => "",
        "image3"        => "",
        "image4"        => "",
        "image5"        => "",
        "video"         => "/01Campominato.mp4",
        "technologies"  => [1, 2, 3],
        "link_github"   => "https://github.com/AlessioAbbati/js-campominato-dom.git",
    ],
    [
        'type_id'       => '1',
        "title"         => "Social Posts",
        "user_id"       => "1",
        "creation_date" => "2023-05-03",
        "last_update"   => "2023-05-03",
        "collaborators" => "",
        "description"   => "clone of social",
        "image1"        => "/01SocialPosts1.jpeg",
        "image2"        => "/01SocialPosts2.jpeg",
        "image3"        => "/01SocialPosts3.jpeg",
        "image4"        => "/01SocialPosts4.jpeg",
        "image5"        => "/01SocialPosts5.jpeg",
        "video"         => "",
        "technologies"  => [1, 2, 3],
        "link_github"   => "https://github.com/AlessioAbbati/js-social-posts.git",
    ],
    [
        'type_id'       => '1',
        "title"         => "Boolzapp",
        "user_id"       => "1",
        "creation_date" => "2023-05-10",
        "last_update"   => "2023-05-16",
        "collaborators" => "",
        "description"   => "clone of whatsapp",
        "image1"        => "/01Boolzapp.jpeg",
        "image2"        => "",
        "image3"        => "",
        "image4"        => "",
        "image5"        => "",
        "video"         => "/01Boolzapp.mp4",
        "technologies"  => [1, 2, 4, 5],
        "link_github"   => "https://github.com/AlessioAbbati/vue-boolzapp.git",
    ],
    [
        'type_id'       => '1',
        "title"         => "Boolflix",
        "user_id"       => "1",
        "creation_date" => "2023-05-24",
        "last_update"   => "2023-05-26",
        "collaborators" => "",
        "description"   => "clone of netflix",
        "image1"        => "/01Boolflix.jpeg",
        "image2"        => "",
        "image3"        => "",
        "image4"        => "",
        "image5"        => "",
        "video"         => "/01Boolflix.mp4",
        "technologies"  => [1, 2, 4, 5],
        "link_github"   => "https://github.com/AlessioAbbati/vite-boolflix.git",
    ],
    [
        'type_id'       => '1',
        "title"         => "Football League",
        "user_id"       => "1",
        "creation_date" => "2023-05-29",
        "last_update"   => "2023-06-06",
        "collaborators" => "",
        "description"   => "clone of football league page",
        "image1"        => "/01FootballLeague1.jpeg",
        "image2"        => "/01FootballLeague2.jpeg",
        "image3"        => "/01FootballLeague3.jpeg",
        "image4"        => "/01FootballLeague4.jpeg",
        "image5"        => "/01FootballLeague5.jpeg",
        "video"         => "",
        "technologies"  => [1, 2, 4, 5],
        "link_github"   => "https://github.com/AlessioAbbati/proj-html-vuejs.git",
    ],
    [
        'type_id'       => '2',
        "title"         => "Travel Agency",
        "user_id"       => "1",
        "creation_date" => "2023-07-04",
        "last_update"   => "2023-07-04",
        "collaborators" => "Felice D'Arcangelo - Lamberto Neri - Nicola Soggiu - Giulio D'Angelo - Domenico Ferrari",
        "description"   => "clone of travel agency",
        "image1"        => "/01LaravelBoolean1.jpeg",
        "image2"        => "/01LaravelBoolean2.jpeg",
        "image3"        => "/01LaravelBoolean3.jpeg",
        "image4"        => "/01LaravelBoolean4.jpeg",
        "image5"        => "",
        "video"         => "/01LaravelBoolean.mp4",
        "technologies"  => [6, 7],
        "link_github"   => "https://github.com/AlessioAbbati/laravel-boolean.git",
    ],
    [
        "type_id"       => "1",
        "title"         => "Spotify Web",
        "user_id"       => "2",
        "creation_date" => "2023-03-22",
        "last_update"   => "2023-03-27",
        "collaborators" => "No",
        "description"   => "A clone of the spotify web interface",
        "image1"        => "/02SpotifyWeb_01.png",
        "image2"        => "/02SpotifyWeb_02.png",
        "image3"        => "/02SpotifyWeb_03.png",
        "image4"        => "/02SpotifyWeb_04.png",
        "image5"        => "/02SpotifyWeb_05.png",
        "video"         => "/02SpotifyWeb_video.mp4",
        "technologies"  => [1, 2],
        "link_github"   => "https://github.com/antoniodangelo11/html-css-spotifyweb.git",
    ],
    [
        "type_id"       => "1",
        "title"         => "Minefield",
        "user_id"       => "2",
        "creation_date" => "2023-04-26",
        "last_update"   => "2023-04-27",
        "collaborators" => "No",
        "description"   => "A minefield clone",
        "image1"        => "/02Campominato_01.png",
        "image2"        => "/02Campominato_02.png",
        "image3"        => "/02Campominato_03.png",
        "image4"        => "/02Campominato_04.png",
        "image5"        => "/02Campominato_05.png",
        "video"         => "/02Campominato_video.mp4",
        "technologies"  => [1, 2, 3],
        "link_github"   => "https://github.com/antoniodangelo11/js-campominato-dom.git",
    ],
    [
        "type_id"       => "1",
        "title"         => "Social Post",
        "user_id"       => "2",
        "creation_date" => "2023-05-03",
        "last_update"   => "2023-05-04",
        "collaborators" => "No",
        "description"   => "A Facebook clone",
        "image1"        => "/02SocialPost_01.png",
        "image2"        => "/02SocialPost_02.png",
        "image3"        => "/02SocialPost_03.png",
        "image4"        => "/02SocialPost_04.png",
        "image5"        => "/02SocialPost_05.png",
        "video"         => "/02SocialPost_video.mp4",
        "technologies"  => [1, 2, 3],
        "link_github"   => "https://github.com/antoniodangelo11/js-social-posts.git",
    ],
    [
        "type_id"       => "1",
        "title"         => "Boolzapp",
        "user_id"       => "2",
        "creation_date" => "2023-05-10",
        "last_update"   => "2023-05-15",
        "collaborators" => "No",
        "description"   => "A Whatsapp clone",
        "image1"        => "/02Boolzapp_01.png",
        "image2"        => "/02Boolzapp_02.png",
        "image3"        => "/02Boolzapp_03.png",
        "image4"        => "/02Boolzapp_04.png",
        "image5"        => "/02Boolzapp_05.png",
        "video"         => "/02Boolzapp_video.mp4",
        "technologies"  => [4, 5],
        "link_github"   => "https://github.com/antoniodangelo11/vue-boolzapp.git",
    ],
    [
        "type_id"       => "1",
        "title"         => "Avada Driving",
        "user_id"       => "2",
        "creation_date" => "2023-05-29",
        "last_update"   => "2023-05-31",
        "collaborators" => "No",
        "description"   => "Avada Driving clone",
        "image1"        => "/02AvadaDriving_01.png",
        "image2"        => "/02AvadaDriving_02.png",
        "image3"        => "/02AvadaDriving_03.png",
        "image4"        => "/02AvadaDriving_04.png",
        "image5"        => "/02AvadaDriving_05.png",
        "video"         => "/02AvadaDriving_video.mp4",
        "technologies"  => [4, 5],
        "link_github"   => "https://github.com/antoniodangelo11/proj-html-vuejs.git",
    ],
    [
        "type_id"       => "2",
        "title"         => "DC Comics",
        "user_id"       => "2",
        "creation_date" => "2023-06-29",
        "last_update"   => "2023-07-03",
        "collaborators" => "No",
        "description"   => "A Dc Comics site homepage clone",
        "image1"        => "/02LaravelDc_01.png",
        "image2"        => "/02LaravelDc_02.png",
        "image3"        => "/02LaravelDc_03.png",
        "image4"        => "/02LaravelDc_04.png",
        "image5"        => "/02LaravelDc_05.png",
        "video"         => "/02LaravelDc_video.mp4",
        "technologies"  => [6, 7],
        "link_github"   => "https://github.com/antoniodangelo11/laravel-dc-comics.git",
    ],
    [
        "type_id"       => "3",
        "title"         => "Laravel Boolean",
        "user_id"       => "2",
        "creation_date" => "2023-07-04",
        "last_update"   => "2023-07-004",
        "collaborators" => "Antonio D'Angelo, Luca Casamassima, Davide Farci, Loris Marzocchi",
        "description"   => "A invoices organizer",
        "image1"        => "/02LaravelInvoices_01.png",
        "image2"        => "/02LaravelInvoices_02.png",
        "image3"        => "/02LaravelInvoices_03.png",
        "image4"        => "/02LaravelInvoices_04.png",
        "image5"        => "/02LaravelInvoices_05.png",
        "video"         => "/02LaravelInvoices_video.mp4",
        "technologies"  => [6, 7],
        "link_github"   => "https://github.com/SimoneRicco/laravel-boolean.git",
    ],
    [
        'type_id'       => '1',
        "title"         => "Spotify Web",
        "user_id"       => "3",
        "creation_date" => "2023-03-22",
        "last_update"   => "2023-03-27",
        "collaborators" => "",
        "description"   => "A clone of Spotify Web",
        "image1"        => "/02-spotify-01",
        "image2"        => "/02-spotify-02",
        "image3"        => "/02-spotify-03",
        "image4"        => "/02-spotify-04",
        "image5"        => "",
        "video"         => "/02-spotify-video.webm",
        "technologies"  => [1, 2],
        "link_github"   => "https://github.com/DavideFarci/html-css-spotifyweb.git",
    ],
    [
        'type_id'       => '1',
        "title"         => "Campominato",
        "user_id"       => "3",
        "creation_date" => "2023-04-02",
        "last_update"   => "2023-04-07",
        "collaborators" => "",
        "description"   => "A clone of Minefield",
        "image1"        => "/02-campominato-01",
        "image2"        => "/02-campominato-02",
        "image3"        => "/02-campominato-03",
        "image4"        => "",
        "image5"        => "",
        "video"         => "/02-campominato-video.webm",
        "technologies"  => [1, 2, 3],
        "link_github"   => "https://github.com/DavideFarci/js-campominato-dom.git",
    ],
    [
        'type_id'       => '1',
        "title"         => "Social Post",
        "user_id"       => "3",
        "creation_date" => "2023-05-03",
        "last_update"   => "2023-05-03",
        "collaborators" => "",
        "description"   => "A clone of Facebook",
        "image1"        => "/02-social-post-01",
        "image2"        => "/02-social-post-02",
        "image3"        => "",
        "image4"        => "",
        "image5"        => "",
        "video"         => "/02-social-post-video.webm",
        "technologies"  => [1, 2, 3],
        "link_github"   => "https://github.com/DavideFarci/js-social-posts.git",
    ],
    [
        'type_id'       => '1',
        "title"         => "BoolzApp",
        "user_id"       => "3",
        "creation_date" => "2023-05-10",
        "last_update"   => "2023-06-06",
        "collaborators" => "",
        "description"   => "A clone of WhatsApp",
        "image1"        => "/02-boolzapp-01",
        "image2"        => "/02-boolzapp-02",
        "image3"        => "",
        "image4"        => "",
        "image5"        => "",
        "video"         => "/02-boolzapp-video.webm",
        "technologies"  => [1, 2, 3],
        "link_github"   => "https://github.com/DavideFarci/vue-boolzapp.git",
    ],
    [
        'type_id'       => '1',
        "title"         => "BoolFlix",
        "user_id"       => "3",
        "creation_date" => "2023-05-24",
        "last_update"   => "2023-06-26",
        "collaborators" => "",
        "description"   => "A clone of Nelflix",
        "image1"        => "/02-boolflix-01",
        "image2"        => "/02-boolflix-02",
        "image3"        => "/02-boolflix-03",
        "image4"        => "",
        "image5"        => "",
        "video"         => "/02-boolflix-video.webm",
        "technologies"  => [1, 2, 4],
        "link_github"   => "https://github.com/DavideFarci/vite-boolflix.gitt",
    ],
    [
        'type_id'       => '1',
        "title"         => "Project Html-VueJs",
        "user_id"       => "3",
        "creation_date" => "2023-05-29",
        "last_update"   => "2023-06-05",
        "collaborators" => "",
        "description"   => "A clone of Website",
        "image1"        => "/02-html-vuejs-01",
        "image2"        => "/02-html-vuejs-02",
        "image3"        => "/02-html-vuejs-03",
        "image4"        => "/02-html-vuejs-04",
        "image5"        => "/02-html-vuejs-05",
        "video"         => "/02-html-vuejs-video.webm",
        "technologies"  => [1, 2, 4],
        "link_github"   => "https://github.com/DavideFarci/vite-boolflix.gitt",
    ],
    [
        'type_id'       => '2',
        "title"         => "DC Comics",
        "user_id"       => "3",
        "creation_date" => "2023-06-29",
        "last_update"   => "2023-07-03",
        "collaborators" => "",
        "description"   => "A clone of a Website of DC Comics",
        "image1"        => "/02-dc-comics-01",
        "image2"        => "/02-dc-comics-02",
        "image3"        => "/02-dc-comics-03",
        "image4"        => "",
        "image5"        => "",
        "video"         => "/02-dc-comics-video.webm",
        "technologies"  => [5, 6],
        "link_github"   => "https://github.com/DavideFarci/laravel-dc-comics.git",
    ],
    [
        'type_id'       => '3',
        "title"         => "Laravel Boolean",
        "user_id"       => "3",
        "creation_date" => "2023-07-04",
        "last_update"   => "2023-07-04",
        "collaborators" => "Antonio D'Angelo, Luca Casamassima, Davide Farci, Loris Marzocchi",
        "description"   => "A invoices organizer",
        "image1"        => "/02-invoices-01",
        "image2"        => "/02-invoices-02",
        "image3"        => "/02-invoices-03",
        "image4"        => "",
        "image5"        => "",
        "video"         => "/02-invoices-video.webm",
        "technologies"  => [5, 6, 4],
        "link_github"   => "https://github.com/SimoneRicco/laravel-boolean.git",
    ],
    [
        "title"         => "Spotify Web",
        "user_id"       => "4",
        "creation_date" => "2023-03-22",
        "last_update"   => "2023-03-27",
        "collaborators" => "No",
        "image1"        => "/04spotifyweb.png",
        "image2"        => "",
        "image3"        => "",
        "image4"        => "",
        "image5"        => "",
        "video"         => "",
        "description"   => "A clone of the spotify web interface",
        "technologies"  => [1, 2],
        "type_id"       => 1,
        "link_github"   => "https://github.com/Paolo96700/html-css-spotifyweb.git",
    ],
    [
        "title"         => "Campo Minato",
        "user_id"       => "4",
        "creation_date" => "2023-04-26",
        "last_update"   => "2023-04-27",
        "collaborators" => "No",
        "image1"        => "/04campominato.png",
        "image2"        => "",
        "image3"        => "",
        "image4"        => "",
        "image5"        => "",
        "video"         => "",
        "description"   => "A minefield clone",
        "technologies"  => [1, 2, 3],
        "type_id"       => 1,
        "link_github"   => "https://github.com/Paolo96700/js-campominato-dom.git",
    ],
    [
        "title"         => "Social Post",
        "user_id"       => "4",
        "creation_date" => "2023-05-03",
        "last_update"   => "2023-05-04",
        "collaborators" => "No",
        "image1"        => "/04socialpost.png",
        "image2"        => "",
        "image3"        => "",
        "image4"        => "",
        "image5"        => "",
        "video"         => "",
        "description"   => "A Facebook clone",
        "technologies"  => [1, 2, 3],
        "type_id"       => 1,
        "link_github"   => "https://github.com/Paolo96700/js-social-posts.git",
    ],
    [
        "title"         => "Boolzapp",
        "user_id"       => "4",
        "creation_date" => "2023-05-10",
        "last_update"   => "2023-05-15",
        "collaborators" => "No",
        "image1"        => "/04boolzapp.png",
        "image2"        => "",
        "image3"        => "",
        "image4"        => "",
        "image5"        => "",
        "video"         => "",
        "description"   => "A Whatsapp clone",
        "technologies"  => [4, 5],
        "type_id"       => 1,
        "link_github"   => "https://github.com/Paolo96700/vite-boolflix.git",
    ],
    [
        "title"         => "School Chess",
        "user_id"       => "4",
        "creation_date" => "2023-05-29",
        "last_update"   => "2023-05-31",
        "collaborators" => "No",
        "image1"        => "/04schoolchess.png",
        "image2"        => "",
        "image3"        => "",
        "image4"        => "",
        "image5"        => "",
        "video"         => "",
        "description"   => "School Chess Site",
        "technologies"  => [4, 5],
        "type_id"       => 1,
        "link_github"   => "https://github.com/Paolo96700/proj-html-vuejs.git",
    ],
    [
        "title"         => "DC Comics",
        "user_id"       => "4",
        "creation_date" => "2023-06-29",
        "last_update"   => "2023-07-03",
        "collaborators" => "No",
        "image1"        => "/04dccomics.png",
        "image2"        => "",
        "image3"        => "",
        "image4"        => "",
        "image5"        => "",
        "video"         => "",
        "description"   => "A Dc Comics site homepage clone",
        "technologies"  => [6, 7],
        "type_id"       => 2,
        "link_github"   => "https://github.com/Paolo96700/laravel-dc-comics.git",
    ],
    [
        "title"         => "Laravel Boolean",
        "user_id"       => "4",
        "creation_date" => "2023-07-04",
        "last_update"   => "2023-07-04",
        "collaborators" => "Paolo Falco, Antonio Nicolaci, Alessandra Casu, Gary Smith Alvarez Venturo, Renato Taccogna, Pierluca Strianese",
        "image1"        => "/04laravelboolean.png",
        "image2"        => "",
        "image3"        => "",
        "image4"        => "",
        "image5"        => "",
        "video"         => "",
        "description"   => "A invoices organizer",
        "technologies"  => [6, 7],
        "type_id"       => 3,
        "link_github"   => "https://github.com/Paolo96700/laravel-boolean.git",
    ],
    [
        "title"         => "Discord",
        "user_id"       => "5",
        "creation_date" => "2023-03-08",
        "last_update"   => "2023-03-08",
        "collaborators" => "No",
        "image1"        => "/05discord.png",
        "image2"        => "",
        "image3"        => "",
        "image4"        => "",
        "image5"        => "",
        "video"         => "/05discord.mp4",
        "description"   => "A Discord clone",
        "technologies"  => [1, 2],
        "type_id"       => 1,
        "link_github"   => "https://github.com/SimoneRicco/htmlcss-discord.git",
    ],
    [
        "title"         => "Yu-Gi-oh",
        "user_id"       => "5",
        "creation_date" => "2023-05-23",
        "last_update"   => "2023-05-23",
        "collaborators" => "No",
        "image1"        => "/05yugioh.png",
        "image2"        => "",
        "image3"        => "",
        "image4"        => "",
        "image5"        => "",
        "video"         => "",
        "description"   => "All Yu-Gi-Oh cards",
        "technologies"  => [1, 2, 3, 4],
        "type_id"       => 1,
        "link_github"   => "https://github.com/SimoneRicco/vite-yu-gi-oh.git",
    ],
    [
        "title"         => "FizzBuzz",
        "user_id"       => "5",
        "creation_date" => "2023-04-14",
        "last_update"   => "2023-04-14",
        "collaborators" => "No",
        "image1"        => "/05fizzbuzz.png",
        "image2"        => "",
        "image3"        => "",
        "image4"        => "",
        "image5"        => "",
        "video"         => "",
        "description"   => "Fizz Buzz exercise",
        "technologies"  => [1, 2, 3],
        "type_id"       => 1,
        "link_github"   => "https://github.com/SimoneRicco/js-fizzbuzz.git",
    ],
    [
        "title"         => "London Trip",
        "user_id"       => "5",
        "creation_date" => "2023-02-24",
        "last_update"   => "2023-02-24",
        "collaborators" => "No",
        "image1"        => "/05londontrip.png",
        "image2"        => "",
        "image3"        => "",
        "image4"        => "",
        "image5"        => "",
        "video"         => "",
        "description"   => "A london trip",
        "technologies"  => [1],
        "type_id"       => 1,
        "link_github"   => "https://github.com/SimoneRicco/html-london-trip.git",
    ],
    [
        "title"         => "Projects api",
        "user_id"       => "5",
        "creation_date" => "2023-07-19",
        "last_update"   => "2023-07-19",
        "collaborators" => "No",
        "image1"        => "/05laravelprojects.png",
        "image2"        => "",
        "image3"        => "",
        "image4"        => "",
        "image5"        => "",
        "video"         => "",
        "description"   => "A database for store all projects",
        "technologies"  => [1,2,3,5,6,7],
        "type_id"       => 2,
        "link_github"   => "https://github.com/SimoneRicco/laravel-api.git",
    ],
    [
        "title"         => "Boolando",
        "user_id"       => "5",
        "creation_date" => "2023-03-09",
        "last_update"   => "2023-03-09",
        "collaborators" => "No",
        "image1"        => "/05boolando.png",
        "image2"        => "",
        "image3"        => "",
        "image4"        => "",
        "image5"        => "",
        "video"         => "",
        "description"   => "A copy of Zalando's site",
        "technologies"  => [1,2],
        "type_id"       => 1,
        "link_github"   => "https://github.com/SimoneRicco/html-css-boolando.git",
    ],
    [
        "title"         => "Boolzapp",
        "user_id"       => "5",
        "creation_date" => "2023-05-12",
        "last_update"   => "2023-05-12",
        "collaborators" => "No",
        "image1"        => "/05boolzapp.png",
        "image2"        => "",
        "image3"        => "",
        "image4"        => "",
        "image5"        => "",
        "video"         => "",
        "description"   => "A copy of Whatsapp",
        "technologies"  => [1,2,3,4],
        "type_id"       => 1,
        "link_github"   => "https://github.com/SimoneRicco/vue-boolzapp.git",
    ],

    [
        "type_id"       => "1",
        "title"         => "Dropbox",
        "user_id"       => "6",
        "creation_date" => "2023-03-15",
        "last_update"   => "2023-03-16",
        "collaborators" => "",
        "description"   => "Frontend design of the web page of 'Dropbox' the most popular file hosting service.",
        "image1"        => "/06Dropbox.png",
        "image2"        => "",
        "image3"        => "",
        "image4"        => "",
        "image5"        => "",
        "video"         => "",
        "technologies"  => [1, 2],
        "link_github"   => "https://github.com/Andreaserra1997/htmlcss-dropbox",
    ],
    [
        "type_id"       => "1",
        "title"         => "Spotifyweb",
        "user_id"       => "6",
        "creation_date" => "2023-03-22",
        "last_update"   => "2023-03-24",
        "collaborators" => "",
        "description"   => "Frontend design of the web page of 'Spotify' famous Swedish music service.",
        "image1"        => "/06Spotifyweb.png",
        "image2"        => "",
        "image3"        => "",
        "image4"        => "",
        "image5"        => "",
        "video"         => "/06Spotifyweb.webm",
        "technologies"  => [1, 2],
        "link_github"   => "https://github.com/Andreaserra1997/html-css-spotifyweb",
    ],
    [
        "type_id"       => "1",
        "title"         => "WhatsApp",
        "user_id"       => "6",
        "creation_date" => "2023-05-09",
        "last_update"   => "2023-05-12",
        "collaborators" => "",
        "description"   => "Frontend design of the web page of 'WhatsApp' famous messaging service, with the ability to dynamically display the contact list and individual chats, also sending user-written messages.",
        "image1"        => "/06WhatsApp.png",
        "image2"        => "",
        "image3"        => "",
        "image4"        => "",
        "image5"        => "",
        "video"         => "/06WhatsApp.webm",
        "technologies"  => [1, 2, 3],
        "link_github"   => "https://github.com/Andreaserra1997/vue-boolzapp",
    ],
    [
        "type_id"       => "1",
        "title"         => "DC_Comics",
        "user_id"       => "6",
        "creation_date" => "2023-05-19",
        "last_update"   => "2023-05-21",
        "collaborators" => "",
        "description"   => "Frontend design of web page of 'DC Comics' comic book publishing company.",
        "image1"        => "/06DC_Comics.png",
        "image2"        => "",
        "image3"        => "",
        "image4"        => "",
        "image5"        => "",
        "video"         => "",
        "technologies"  => [1, 2, 4, 5],
        "link_github"   => "https://github.com/Andreaserra1997/vite-comics",
    ],
    [
        "type_id"       => "1",
        "title"         => "DogMilo",
        "user_id"       => "6",
        "creation_date" => "2023-05-27",
        "last_update"   => "2023-05-31",
        "collaborators" => "",
        "description"   => "Frontend design of a dog care site",
        "image1"        => "/06DogMilo.png",
        "image2"        => "",
        "image3"        => "",
        "image4"        => "",
        "image5"        => "",
        "video"         => "",
        "technologies"  => [1, 2, 4, 5],
        "link_github"   => "https://github.com/Andreaserra1997/proj-html-vuejs",
    ],
    [
        "type_id"       => "2",
        "title"         => "Laravel_Comics",
        "user_id"       => "6",
        "creation_date" => "2023-06-30",
        "last_update"   => "2023-07-03",
        "collaborators" => "",
        "description"   => "Backend design of an archiving system for publishing DC Comics. Users can view in detail each item, edit them, add new ones, and delete them. In addition, a recycle bin has been implemented that allows retrieval of deleted items.",
        "image1"        => "/06Laravel_Comics.png",
        "image2"        => "",
        "image3"        => "",
        "image4"        => "",
        "image5"        => "",
        "video"         => "/06Laravel_Comics.webm",
        "technologies"  => [1, 2, 6, 7],
        "link_github"   => "https://github.com/Andreaserra1997/laravel-dc-comics",
    ],
    [
        "type_id"       => "3",
        "title"         => "Cocktail Bar",
        "user_id"       => "6",
        "creation_date" => "2023-07-19",
        "last_update"   => "2023-07-21",
        "collaborators" => "Gabriella Valentina Marchese, Gianluca Ligori",
        "description"   => 'Fullstack design of a cocktail site.  Users can see all the cocktails in the database and the details of each. The site also includes an "About Us" page to learn about the team behind the project and a "Contact Us" page to send messages to the team.',
        "image1"        => "/06Cocktail_home.png",
        "image2"        => "/06Cocktail_show.png",
        "image3"        => "/06Cocktail_about.png",
        "image4"        => "/06Cocktail_contact.png",
        "image5"        => "/06Cocktail_filter.png",
        "video"         => "/06Cocktail_Bar.webm",
        "technologies"  => [1, 2, 4, 5, 6, 7],
        "link_github"   => "https://github.com/Andreaserra1997/laravel-vue-router-frontoffice-main",
    ]

];
