<?php

return [
    [
        'type_id' => '1',
        "title" => "SpotifyWeb",
        "user_id" => "1",
        "creation_date" => "2023-03-22",
        "last_update" => "2023-03-27",
        "collaborators" => "",
        "description" => "clone of spotify",
        "image"       => "uploads/SpotifyWeb.jpeg",
        
        "link_github" => "https://github.com/AlessioAbbati/html-css-spotifyweb.git",
    ],
    [
        'type_id' => '1',
        "title" => "Minefield",
        "user_id" => "1",
        "creation_date" => "2023-04-26",
        "last_update" => "2023-04-26",
        "collaborators" => "",
        "description" => "clone of minefield",
        "image"       => "uploads/Campominato.jpeg",
        
        "link_github" => "https://github.com/AlessioAbbati/js-campominato-dom.git",
    ],
    [
        'type_id' => '1',
        "title" => "Social Posts",
        "user_id" => "1",
        "creation_date" => "2023-05-03",
        "last_update" => "2023-05-03",
        "collaborators" => "",
        "description" => "clone of social",
        "image"       => "uploads/SocialPosts.jpeg",
        
        "link_github" => "https://github.com/AlessioAbbati/js-social-posts.git",
    ],
    [
        'type_id' => '1',
        "title" => "Boolzapp",
        "user_id" => "1",
        "creation_date" => "2023-05-10",
        "last_update" => "2023-05-16",
        "collaborators" => "",
        "description" => "clone of whatsapp",
        "image"       => "uploads/Boolzapp.jpeg",
        
        "link_github" => "https://github.com/AlessioAbbati/vue-boolzapp.git",
    ],
    [
        'type_id' => '1',
        "title" => "Boolflix",
        "user_id" => "1",
        "creation_date" => "2023-05-24",
        "last_update" => "2023-05-26",
        "collaborators" => "",
        "description" => "clone of netflix",
        "image"       => "uploads/Boolflix.jpeg",
        
        "link_github" => "https://github.com/AlessioAbbati/vite-boolflix.git",
    ],
    [
        'type_id' => '1',
        "title" => "Football League",
        "user_id" => "1",
        "creation_date" => "2023-05-29",
        "last_update" => "2023-06-06",
        "collaborators" => "",
        "description" => "clone of football league page",
        "image"       => "uploads/FootballLeague.jpeg",
        
        "link_github" => "https://github.com/AlessioAbbati/proj-html-vuejs.git",
    ],
    [
        'type_id' => '2',
        "title" => "Travel Agency",
        "user_id" => "1",
        "creation_date" => "2023-07-04",
        "last_update" => "2023-07-04",
        "collaborators" => "Felice D'Arcangelo - Lamberto Neri - Nicola Soggiu - Giulio D'Angelo - Domenico Ferrari",
        "description" => "clone of travel agency",
        "image"       => "uploads/LaravelBoolean.jpeg",
        
        "link_github" => "https://github.com/AlessioAbbati/laravel-boolean.git",
    ],

    [
        "type_id"          => "1",
        "title"            => "Spotify Web",
        "user_id"           => "3",
        "creation_date"    => "2023-03-22",
        "last_update"      => "2023-03-27",
        "collaborators"    => "",
        "description"      => "A clone of Spotify Web",
        "image"            => "uploads/spotify.png",
        // "technologies"        => [1, 2],
        "link_github"      => "https://github.com/DavideFarci/html-css-spotifyweb.git",
    ],
    [
        "type_id"          => "1",
        "title"            => "Campominato",
        "user_id"           => "3",
        "creation_date"    => "2023-04-06",
        "last_update"      => "2023-05-01",
        "collaborators"    => "",
        "description"      => "A clone of Minefield",
        "image"            => "uploads/campominato.png",
        // "technologies"        => [1, 2, 3],
        "link_github"      => "https://github.com/DavideFarci/js-campominato-dom.git",
    ],
    [
        "type_id"          => "1",
        "title"            => "Social Post",
        "user_id"           => "3",
        "creation_date"    => "2023-05-03",
        "last_update"      => "2023-05-03",
        "collaborators"    => "",
        "description"      => "A clone of Facebook",
        "image"            => "uploads/social_post.png",
        // "technologies"        => [1, 2, 3],
        "link_github"      => "https://github.com/DavideFarci/js-social-posts.git",
    ],
    [
        "type_id"          => "1",
        "title"            => "BoolzApp",
        "user_id"           => "3",
        "creation_date"    => "2023-05-10",
        "last_update"      => "2023-06-06",
        "collaborators"    => "",
        "description"      => "A clone of WhatsApp",
        "image"            => "uploads/boolzapp.png",
        // "technologies"        => [1, 2, 3],
        "link_github"      => "https://github.com/DavideFarci/vue-boolzapp.git",
    ],
    [
        "type_id"          => "1",
        "title"            => "BoolFlix",
        "user_id"           => "3",
        "creation_date"    => "2023-05-24",
        "last_update"      => "2023-06-26",
        "collaborators"    => "",
        "description"      => "A clone of Nelflix",
        "image"            => "uploads/boolflix.png",
        // "technologies"        => [1, 2, 4],
        "link_github"      => "https://github.com/DavideFarci/vite-boolflix.git",
    ],
    [
        "type_id"          => "1",
        "title"            => "Project Html-VueJs",
        "user_id"           => "3",
        "creation_date"    => "2023-05-29",
        "last_update"      => "2023-06-05",
        "collaborators"    => "",
        "description"      => "A clone of a Website",
        "image"            => "uploads/project-html-vueJs.png",
        // "technologies"        => [1, 2, 4],
        "link_github"      => "https://github.com/DavideFarci/proj-html-vuejs.git",
    ],
    [
        "type_id"          => "2",
        "title"            => "DC Comics",
        "user_id"           => "3",
        "creation_date"    => "2023-06-29",
        "last_update"      => "2023-07-03",
        "collaborators"    => "",
        "description"      => "A clone of a Website of DC Comics",
        "image"            => "uploads/dc_comics.png",
        // "technologies"        => [5, 6],
        "link_github"      => "https://github.com/DavideFarci/laravel-dc-comics.git",
    ],
    [
        "type_id"          => "3",
        "title"            => "Laravel Boolean",
        "user_id"           => "5",
        "creation_date"    => "2023-07-04",
        "last_update"      => "2023-07-004",
        "collaborators"    => "Antonio D'Angelo, Luca Casamassima, Davide Farci, Loris Marzocchi",
        "description"      => "A invoices organizer",
        "image"            => "uploads/laravel_boolean.png",
        // "technologies"        => [5, 6, 4],
        "link_github"      => "https://github.com/SimoneRicco/laravel-boolean.git",
    ],

    [
        "title" => "Spotify Web",
        "user_id" => "4",
        "creation_date" => "2023-03-22",
        "last_update" => "2023-03-27",
        "collaborators" => "No",
        "image" => "uploads/spotifyweb.png",
        "description" => "A clone of the spotify web interface",
        // "technologies" => [1, 2],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/html-css-spotifyweb.git",
    ],

    [
        "title" => "Campo Minato",
        "user_id" => "4",
        "creation_date" => "2023-04-26",
        "last_update" => "2023-04-27",
        "collaborators" => "No",
        "image" => "uploads/campominato.png",
        "description" => "A minefield clone",
        // "technologies" => [1, 2, 3],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/js-campominato-dom.git",
    ],

    [
        "title" => "Social Post",
        "user_id" => "4",
        "creation_date" => "2023-05-03",
        "last_update" => "2023-05-04",
        "collaborators" => "No",
        "image" => "uploads/socialpost.png",
        "description" => "A Facebook clone",
        // "technologies" => [1, 2, 3],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/js-social-posts.git",
    ],

    [
        "title" => "Boolzapp",
        "user_id" => "4",
        "creation_date" => "2023-05-10",
        "last_update" => "2023-05-15",
        "collaborators" => "No",
        "image" => "uploads/boolzapp.png",
        "description" => "A Whatsapp clone",
        // "technologies" => [4, 5],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/vite-boolflix.git",
    ],

    [
        "title" => "School Chess",
        "user_id" => "4",
        "creation_date" => "2023-05-29",
        "last_update" => "2023-05-31",
        "collaborators" => "No",
        "image" => "uploads/schoolchess.png",
        "description" => "Avada Driving clone",
        // "technologies" => [4, 5],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/proj-html-vuejs.git",
    ],

    [
        "title" => "DC Comics",
        "user_id" => "4",
        "creation_date" => "2023-06-29",
        "last_update" => "2023-07-03",
        "collaborators" => "No",
        "image" => "uploads/dccomics.png",
        "description" => "A Dc Comics site homepage clone",
        // "technologies" => [6, 7],
        "type_id" => 2,
        "link_github" => "https://github.com/Paolo96700/laravel-dc-comics.git",
    ],

    [
        "title" => "Laravel Boolean",
        "user_id" => "4",
        "creation_date" => "2023-07-04",
        "last_update" => "2023-07-04",
        "collaborators" => "Paolo Falco, Antonio Nicolaci, Alessandra Casu, Gary Smith Alvarez Venturo, Renato Taccogna, Pierluca Strianese",
        "image" => "uploads/laravelboolean.png",
        "description" => "A invoices organizer",
        // "technologies" => [6, 7],
        "type_id" => 3,
        "link_github" => "https://github.com/Paolo96700/laravel-boolean.git",
    ],
    
];