<?php

return [
    [
        'type_id' => '1',
        "title" => "SpotifyWeb",
        "user_id" => "1",
        "creation_date" => "2023-03-22",
        "last_update" => "2023-03-27",
        "collaborators" => "",
        "description" => "clone of spotify",
        "image1"       => "uploads/SpotifyWeb.jpeg",
        "image2"       => "",
        "image3"       => "",
        "image4"       => "",
        "image5"       => "",
        // "video"        => "",
        "technologies" => [1, 2, 3],
        "link_github" => "https://github.com/AlessioAbbati/html-css-spotifyweb.git",
    ],
    [
        'type_id' => '1',
        "title" => "Minefield",
        "user_id" => "1",
        "creation_date" => "2023-04-26",
        "last_update" => "2023-04-26",
        "collaborators" => "",
        "description" => "clone of minefield",
        "image1"       => "uploads/Campominato.jpeg",
        "image2"       => "",
        "image3"       => "",
        "image4"       => "",
        "image5"       => "",
        // "video"        => "",
        "technologies" => [1, 2, 3],
        "link_github" => "https://github.com/AlessioAbbati/js-campominato-dom.git",
    ],
    [
        'type_id' => '1',
        "title" => "Social Posts",
        "user_id" => "1",
        "creation_date" => "2023-05-03",
        "last_update" => "2023-05-03",
        "collaborators" => "",
        "description" => "clone of social",
        "image1"       => "uploads/SocialPosts.jpeg",
        "image2"       => "",
        "image3"       => "",
        "image4"       => "",
        "image5"       => "",
        // "video"        => "",
        "technologies" => [1, 2, 3],
        "link_github" => "https://github.com/AlessioAbbati/js-social-posts.git",
    ],
    [
        'type_id' => '1',
        "title" => "Boolzapp",
        "user_id" => "1",
        "creation_date" => "2023-05-10",
        "last_update" => "2023-05-16",
        "collaborators" => "",
        "description" => "clone of whatsapp",
        "image1"       => "uploads/Boolzapp.jpeg",
        "image2"       => "",
        "image3"       => "",
        "image4"       => "",
        "image5"       => "",
        // "video"        => "",
        "technologies" => [1, 2, 4, 5],
        "link_github" => "https://github.com/AlessioAbbati/vue-boolzapp.git",
    ],
    [
        'type_id' => '1',
        "title" => "Boolflix",
        "user_id" => "1",
        "creation_date" => "2023-05-24",
        "last_update" => "2023-05-26",
        "collaborators" => "",
        "description" => "clone of netflix",
        "image1"       => "uploads/Boolflix.jpeg",
        "image2"       => "",
        "image3"       => "",
        "image4"       => "",
        "image5"       => "",
        // "video"        => "",
        "technologies" => [1, 2, 4, 5],
        "link_github" => "https://github.com/AlessioAbbati/vite-boolflix.git",
    ],
    [
        'type_id' => '1',
        "title" => "Football League",
        "user_id" => "1",
        "creation_date" => "2023-05-29",
        "last_update" => "2023-06-06",
        "collaborators" => "",
        "description" => "clone of football league page",
        "image1"       => "uploads/FootballLeague.jpeg",
        "image2"       => "",
        "image3"       => "",
        "image4"       => "",
        "image5"       => "",
        // "video"        => "",
        "technologies" => [1, 2, 4, 5],
        "link_github" => "https://github.com/AlessioAbbati/proj-html-vuejs.git",
    ],
    [
        'type_id' => '2',
        "title" => "Travel Agency",
        "user_id" => "1",
        "creation_date" => "2023-07-04",
        "last_update" => "2023-07-04",
        "collaborators" => "Felice D'Arcangelo - Lamberto Neri - Nicola Soggiu - Giulio D'Angelo - Domenico Ferrari",
        "description" => "clone of travel agency",
        "image1"       => "uploads/LaravelBoolean.jpeg",
        "image2"       => "",
        "image3"       => "",
        "image4"       => "",
        "image5"       => "",
        // "video"        => "",
        "technologies" => [6, 7],
        "link_github" => "https://github.com/AlessioAbbati/laravel-boolean.git",
    ],

    [
        "type_id"          => "1",
        "title"            => "Spotify Web",
        "user_id"           => "3",
        "creation_date"    => "2023-03-22",
        "last_update"      => "2023-03-27",
        "collaborators"    => "",
        "description"      => "A clone of Spotify Web",
        "image1"            => "uploads/spotify.png",
        "image2"       => "",
        "image3"       => "",
        "image4"       => "",
        "image5"       => "",
        // "video"        => "",
        "technologies"        => [1, 2],
        "link_github"      => "https://github.com/DavideFarci/html-css-spotifyweb.git",
    ],
    [
        "type_id"          => "1",
        "title"            => "Campominato",
        "user_id"           => "3",
        "creation_date"    => "2023-04-06",
        "last_update"      => "2023-05-01",
        "collaborators"    => "",
        "description"      => "A clone of Minefield",
        "image1"            => "uploads/campominato.png",
        "image2"       => "",
        "image3"       => "",
        "image4"       => "",
        "image5"       => "",
        // "video"        => "",
        "technologies"        => [1, 2, 3],
        "link_github"      => "https://github.com/DavideFarci/js-campominato-dom.git",
    ],
    [
        "type_id"          => "1",
        "title"            => "Social Post",
        "user_id"           => "3",
        "creation_date"    => "2023-05-03",
        "last_update"      => "2023-05-03",
        "collaborators"    => "",
        "description"      => "A clone of Facebook",
        "image1"            => "uploads/social_post.png",
        "image2"       => "",
        "image3"       => "",
        "image4"       => "",
        "image5"       => "",
        // "video"        => "",
        "technologies"        => [1, 2, 3],
        "link_github"      => "https://github.com/DavideFarci/js-social-posts.git",
    ],
    [
        "type_id"          => "1",
        "title"            => "BoolzApp",
        "user_id"           => "3",
        "creation_date"    => "2023-05-10",
        "last_update"      => "2023-06-06",
        "collaborators"    => "",
        "description"      => "A clone of WhatsApp",
        "image1"            => "uploads/boolzapp.png",
        "image2"       => "",
        "image3"       => "",
        "image4"       => "",
        "image5"       => "",
        // "video"        => "",
        "technologies"        => [1, 2, 3],
        "link_github"      => "https://github.com/DavideFarci/vue-boolzapp.git",
    ],
    [
        "type_id"          => "1",
        "title"            => "BoolFlix",
        "user_id"           => "3",
        "creation_date"    => "2023-05-24",
        "last_update"      => "2023-06-26",
        "collaborators"    => "",
        "description"      => "A clone of Nelflix",
        "image1"            => "uploads/boolflix.png",
        "image2"       => "",
        "image3"       => "",
        "image4"       => "",
        "image5"       => "",
        // "video"        => "",
        "technologies"        => [1, 2, 4],
        "link_github"      => "https://github.com/DavideFarci/vite-boolflix.git",
    ],
    [
        "type_id"          => "1",
        "title"            => "Project Html-VueJs",
        "user_id"           => "3",
        "creation_date"    => "2023-05-29",
        "last_update"      => "2023-06-05",
        "collaborators"    => "",
        "description"      => "A clone of a Website",
        "image1"            => "uploads/project-html-vueJs.png",
        "image2"       => "",
        "image3"       => "",
        "image4"       => "",
        "image5"       => "",
        // "video"        => "",
        "technologies"        => [1, 2, 4],
        "link_github"      => "https://github.com/DavideFarci/proj-html-vuejs.git",
    ],
    [
        "type_id"          => "2",
        "title"            => "DC Comics",
        "user_id"           => "3",
        "creation_date"    => "2023-06-29",
        "last_update"      => "2023-07-03",
        "collaborators"    => "",
        "description"      => "A clone of a Website of DC Comics",
        "image1"            => "uploads/dc_comics.png",
        "image2"       => "",
        "image3"       => "",
        "image4"       => "",
        "image5"       => "",
        // "video"        => "",
        "technologies"        => [5, 6],
        "link_github"      => "https://github.com/DavideFarci/laravel-dc-comics.git",
    ],
    [
        "type_id"          => "3",
        "title"            => "Laravel Boolean",
        "user_id"           => "5",
        "creation_date"    => "2023-07-04",
        "last_update"      => "2023-07-004",
        "collaborators"    => "Antonio D'Angelo, Luca Casamassima, Davide Farci, Loris Marzocchi",
        "description"      => "A invoices organizer",
        "image1"            => "uploads/laravel_boolean.png",
        "image2"       => "",
        "image3"       => "",
        "image4"       => "",
        "image5"       => "",
        // "video"        => "",
        "technologies"        => [5, 6, 4],
        "link_github"      => "https://github.com/SimoneRicco/laravel-boolean.git",
    ],

    [
        "title" => "Spotify Web",
        "user_id" => "4",
        "creation_date" => "2023-03-22",
        "last_update" => "2023-03-27",
        "collaborators" => "No",
        "image1" => "uploads/spotifyweb.png",
        "image2"       => "",
        "image3"       => "",
        "image4"       => "",
        "image5"       => "",
        // "video"        => "",
        "description" => "A clone of the spotify web interface",
        "technologies" => [1, 2],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/html-css-spotifyweb.git",
    ],

    [
        "title" => "Campo Minato",
        "user_id" => "4",
        "creation_date" => "2023-04-26",
        "last_update" => "2023-04-27",
        "collaborators" => "No",
        "image1" => "uploads/campominato.png",
        "image2"       => "",
        "image3"       => "",
        "image4"       => "",
        "image5"       => "",
        // "video"        => "",
        "description" => "A minefield clone",
        "technologies" => [1, 2, 3],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/js-campominato-dom.git",
    ],

    [
        "title" => "Social Post",
        "user_id" => "4",
        "creation_date" => "2023-05-03",
        "last_update" => "2023-05-04",
        "collaborators" => "No",
        "image1" => "uploads/socialpost.png",
        "image2"       => "",
        "image3"       => "",
        "image4"       => "",
        "image5"       => "",
        // "video"        => "",
        "description" => "A Facebook clone",
        "technologies" => [1, 2, 3],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/js-social-posts.git",
    ],

    [
        "title" => "Boolzapp",
        "user_id" => "4",
        "creation_date" => "2023-05-10",
        "last_update" => "2023-05-15",
        "collaborators" => "No",
        "image1" => "uploads/boolzapp.png",
        "image2"       => "",
        "image3"       => "",
        "image4"       => "",
        "image5"       => "",
        // "video"        => "",
        "description" => "A Whatsapp clone",
        "technologies" => [4, 5],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/vite-boolflix.git",
    ],

    [
        "title" => "School Chess",
        "user_id" => "4",
        "creation_date" => "2023-05-29",
        "last_update" => "2023-05-31",
        "collaborators" => "No",
        "image1" => "uploads/schoolchess.png",
        "image2"       => "",
        "image3"       => "",
        "image4"       => "",
        "image5"       => "",
        // "video"        => "",
        "description" => "Avada Driving clone",
        "technologies" => [4, 5],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/proj-html-vuejs.git",
    ],

    [
        "title" => "DC Comics",
        "user_id" => "4",
        "creation_date" => "2023-06-29",
        "last_update" => "2023-07-03",
        "collaborators" => "No",
        "image1" => "uploads/dccomics.png",
        "image2"       => "",
        "image3"       => "",
        "image4"       => "",
        "image5"       => "",
        // "video"        => "",
        "description" => "A Dc Comics site homepage clone",
        "technologies" => [6, 7],
        "type_id" => 2,
        "link_github" => "https://github.com/Paolo96700/laravel-dc-comics.git",
    ],

    [
        "title" => "Laravel Boolean",
        "user_id" => "4",
        "creation_date" => "2023-07-04",
        "last_update" => "2023-07-04",
        "collaborators" => "Paolo Falco, Antonio Nicolaci, Alessandra Casu, Gary Smith Alvarez Venturo, Renato Taccogna, Pierluca Strianese",
        "image1" => "uploads/laravelboolean.png",
        "image2"       => "",
        "image3"       => "",
        "image4"       => "",
        "image5"       => "",
        // "video"        => "",
        "description" => "A invoices organizer",
        "technologies" => [6, 7],
        "type_id" => 3,
        "link_github" => "https://github.com/Paolo96700/laravel-boolean.git",
    ],

    [
        "type_id"          => "1",
        "title"            => "Spotify Web",
        "user_id"          => "2",
        "creation_date"    => "2023-03-22",
        "last_update"      => "2023-03-27",
        "collaborators"    => "No",
        "description"      => "A clone of the spotify web interface",
        "image1"            => "uploads/SpotifyWeb.png",
        "image2"       => "",
        "image3"       => "",
        "image4"       => "",
        "image5"       => "",
        // "video"        => "",
        "technologies"     => [1, 2],
        "link_github"      => "https://github.com/antoniodangelo11/html-css-spotifyweb.git",
    ],
    [
        "type_id"          => "1",
        "title"            => "Minefield",
        "user_id"          => "2",
        "creation_date"    => "2023-04-26",
        "last_update"      => "2023-04-27",
        "collaborators"    => "No",
        "description"      => "A minefield clone",
        "image1"            => "uploads/Minefield.png",
        "image2"       => "",
        "image3"       => "",
        "image4"       => "",
        "image5"       => "",
        // "video"        => "",
        "technologies"     => [1, 2, 3],
        "link_github"      => "https://github.com/antoniodangelo11/js-campominato-dom.git",
    ],
    [
        "type_id"          => "1",
        "title"            => "Social Post",
        "user_id"          => "2",
        "creation_date"    => "2023-05-03",
        "last_update"      => "2023-05-04",
        "collaborators"    => "No",
        "description"      => "A Facebook clone",
        "image1"            => "uploads/SocialsPost.png",
        "image2"       => "",
        "image3"       => "",
        "image4"       => "",
        "image5"       => "",
        // "video"        => "",
        "technologies"     => [1, 2, 3],
        "link_github"      => "https://github.com/antoniodangelo11/js-social-posts.git",
    ],
    [
        "type_id"          => "1",
        "title"            => "Boolzapp",
        "user_id"          => "2",
        "creation_date"    => "2023-05-10",
        "last_update"      => "2023-05-15",
        "collaborators"    => "No",
        "description"      => "A Whatsapp clone",
        "image1"            => "uploads/Boolzap.png",
        "image2"       => "",
        "image3"       => "",
        "image4"       => "",
        "image5"       => "",
        // "video"        => "",
        "technologies"     => [4, 5],
        "link_github"      => "https://github.com/antoniodangelo11/vue-boolzapp.git",
    ],
    [
        "type_id"          => "1",
        "title"            => "Avada Driving",
        "user_id"          => "2",
        "creation_date"    => "2023-05-29",
        "last_update"      => "2023-05-31",
        "collaborators"    => "No",
        "description"      => "Avada Driving clone",
        "image1"            => "uploads/AvadaDriving.png",
        "image2"       => "",
        "image3"       => "",
        "image4"       => "",
        "image5"       => "",
        // "video"        => "",
        "technologies"     => [4, 5],
        "link_github"      => "https://github.com/antoniodangelo11/proj-html-vuejs.git",
    ],
    [
        "type_id"          => "2",
        "title"            => "DC Comics",
        "user_id"          => "2",
        "creation_date"    => "2023-06-29",
        "last_update"      => "2023-07-03",
        "collaborators"    => "No",
        "description"      => "A Dc Comics site homepage clone",
        "image1"            => "uploads/LaravelDCcomics.png",
        "image2"       => "",
        "image3"       => "",
        "image4"       => "",
        "image5"       => "",
        // "video"        => "",
        "technologies"     => [6, 7],
        "link_github"      => "https://github.com/antoniodangelo11/laravel-dc-comics.git",
    ],
    [
        "type_id"          => "3",
        "title"            => "Laravel Boolean",
        "user_id"          => "2",
        "creation_date"    => "2023-07-04",
        "last_update"      => "2023-07-004",
        "collaborators"    => "Antonio D'Angelo, Luca Casamassima, Davide Farci, Loris Marzocchi",
        "description"      => "A invoices organizer",
        "image1"            => "uploads/LaravelBoolean.png",
        "image2"       => "",
        "image3"       => "",
        "image4"       => "",
        "image5"       => "",
        // "video"        => "",
        "technologies"     => [6, 7],
        "link_github"      => "https://github.com/SimoneRicco/laravel-boolean.git",
    ],

    [
        "type_id" 		=> "1",
        "title" 		=> "Dropbox",
        "user_id" 		=> "6",
        "creation_date" 	=> "2023-03-15",
        "last_update" 		=> "2023-03-16",
        "collaborators" 	=> "",
        "description" 		=> "Frontend design of the web page of 'Dropbox' the most popular file hosting service.",
        "image1" 		=> "uploads/Dropbox.png",
        "image2"       => "",
        "image3"       => "",
        "image4"       => "",
        "image5"       => "",
        // "video"        => "",
        "technologies" 		=> [1, 2],
        "link_github" 		=> "https://github.com/Andreaserra1997/htmlcss-dropbox",
    ],
    [
        "type_id" 		=> "1",
        "title" 		=> "Spotifyweb",
        "user_id" 		=> "6",
        "creation_date" 	=> "2023-03-22",
        "last_update" 		=> "2023-03-24",
        "collaborators" 	=> "",
        "description" 		=> "Frontend design of the web page of 'Spotify' famous Swedish music service.",
        "image1" 		=> "uploads/Spotifyweb.png",
        "image2"       => "",
        "image3"       => "",
        "image4"       => "",
        "image5"       => "",
        // "video"        => "",
        "technologies" 		=> [1, 2],
        "link_github" 		=> "https://github.com/Andreaserra1997/html-css-spotifyweb",
    ],
    [
        "type_id" 		=> "1",
        "title" 		=> "WhatsApp",
        "user_id" 		=> "6",
        "creation_date" 	=> "2023-05-09",
        "last_update" 		=> "2023-05-12",
        "collaborators" 	=> "",
        "description" 		=> "Frontend design of the web page of 'WhatsApp' famous messaging service, with the ability to dynamically display the contact list and individual chats, also sending user-written messages.",
        "image1" 		=> "uploads/WhatsApp.png",
        "image2"       => "",
        "image3"       => "",
        "image4"       => "",
        "image5"       => "",
        // "video"        => "",
        "technologies" 		=> [1, 2, 3],
        "link_github" 		=> "https://github.com/Andreaserra1997/vue-boolzapp",
    ],
    [
        "type_id" 		=> "1",
        "title" 		=> "DC_Comics",
        "user_id" 		=> "6",
        "creation_date" 	=> "2023-05-19",
        "last_update" 		=> "2023-05-21",
        "collaborators" 	=> "",
        "description" 		=> "Frontend design of web page of 'DC Comics' comic book publishing company.",
        "image1" 		=> "uploads/DC_Comics.png",
        "image2"       => "",
        "image3"       => "",
        "image4"       => "",
        "image5"       => "",
        // "video"        => "",
        "technologies" 		=> [1, 2, 4, 5],
        "link_github" 		=> "https://github.com/Andreaserra1997/vite-comics",
    ],
    [
        "type_id" 		=> "1",
        "title" 		=> "DogMilo",
        "user_id" 		=> "6",
        "creation_date" 	=> "2023-05-27",
        "last_update" 		=> "2023-05-31",
        "collaborators" 	=> "",
        "description" 		=> "Frontend design of a dog care site",
        "image1" 		=> "uploads/DogMilo.png",
        "image2"       => "",
        "image3"       => "",
        "image4"       => "",
        "image5"       => "",
        // "video"        => "",
        "technologies" 		=> [1, 2, 4, 5],
        "link_github" 		=> "https://github.com/Andreaserra1997/proj-html-vuejs",
    ],
    [
        "type_id" 		=> "2",
        "title" 		=> "Laravel_Comics",
        "user_id" 		=> "6",
        "creation_date" 	=> "2023-06-30",
        "last_update" 		=> "2023-07-03",
        "collaborators" 	=> "",
        "description" 		=> "Backend design of an archiving system for publishing DC Comics. Users can view in detail each item, edit them, add new ones, and delete them. In addition, a recycle bin has been implemented that allows retrieval of deleted items.",
        "image1" 		=> "uploads/Laravel_Comics.png",
        "image2"       => "",
        "image3"       => "",
        "image4"       => "",
        "image5"       => "",
        // "video"        => "",
        "technologies" 		=> [1, 2, 6, 7],
        "link_github" 		=> "https://github.com/Andreaserra1997/laravel-dc-comics",
    ],
    [
        "type_id" 		=> "3",
        "title" 		=> "Cocktail Bar",
        "user_id" 		=> "6",
        "creation_date" 	=> "2023-07-19",
        "last_update" 		=> "2023-07-21",
        "collaborators" 	=> "Gabriella Valentina Marchese, Gianluca Ligori",
        "description" 		=> 'Fullstack design of a cocktail site.  Users can see all the cocktails in the database and the details of each. The site also includes an "About Us" page to learn about the team behind the project and a "Contact Us" page to send messages to the team.',
        "image1" 		=> "uploads/Cocktail_Bar.png",
        "image2"       => "",
        "image3"       => "",
        "image4"       => "",
        "image5"       => "",
        // "video"        => "",
        "technologies" 		=> [1, 2, 4, 5, 6, 7],
        "link_github" 		=> "https://github.com/Andreaserra1997/laravel-vue-router-frontoffice-main",
    ]
    
];